lavafed/urls.py
# -*- coding: utf-8 -*-
# vim: set ts=4

# Copyright 2018 Rémi Duraffort
# This file is part of lavafed.
#
# lavafed is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# lavafed is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with lavafed.  If not, see <http://www.gnu.org/licenses/>

from django.conf.urls import url

from . import views as v


urlpatterns = [
    url(r"^$", v.home, name="home"),
    url(r"^devices/$", v.devices, name="devices"),
    url(r"^devices/(?P<lab>[^/]+)/$", v.devices, name="devices.lab"),
    url(
        r"^devices/(?P<lab>[^/]+)/(?P<device>[^/]+)/$",
        v.device_show,
        name="device.show",
    ),
    url(r"^device-types/$", v.device_types, name="device_types"),
    url(
        r"^device-types/(?P<name>[^/]+)/$", v.device_type_show, name="device_types.show"
    ),
    url(r"^labs/$", v.labs, name="labs"),
    url(r"^labs/(?P<lab>[^/]+)/$", v.lab_show, name="labs.show"),
    url(r"^versions/$", v.versions, name="versions"),
    url(r"^versions/latest/$", v.version_show_latest, name="versions.show_latest"),
    url(r"^versions/(?P<version>[^/]+)/$", v.version_show, name="versions.show"),
    url(
        r"^versions/latest/badge/$",
        v.version_badge_latest,
        name="versions.badge_latest",
    ),
    url(
        r"^versions/(?P<version>[^/]+)/badge/$", v.version_badge, name="versions.badge"
    ),
    url(r"^api/v0.1/jobs/$", v.api_v0_1_jobs, name="api.v0.1.jobs"),
    url(
        r"^api/v0.1/versions/(?P<version>[^/]+)/$",
        v.api_v0_1_versions_show,
        name="api.v0.1.versions.show",
    ),
]

lavafed/models.py
# -*- coding: utf-8 -*-
# vim: set ts=4

# Copyright 2018 Rémi Duraffort
# This file is part of lavafed.
#
# lavafed is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# lavafed is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with lavafed.  If not, see <http://www.gnu.org/licenses/>

import random

from django.db import models


def _make_secret():
    # Set of valid characters for secret
    _SECRET_CHARS = "01234567890abcdefghijklmnopqrtsuwxyz"
    return "".join((random.SystemRandom().choice(_SECRET_CHARS) for i in range(64)))


class Device(models.Model):
    class Meta:
        unique_together = ("name", "lab")
        indexes = [models.Index(fields=["name", "lab"])]

    name = models.CharField(blank=False, max_length=200)
    dt = models.ForeignKey("DeviceType", on_delete=models.CASCADE)
    lab = models.ForeignKey("Lab", on_delete=models.CASCADE)
    acquired = models.BooleanField(blank=False, default=False)

    HEALTH_GOOD, HEALTH_UNKNOWN, HEALTH_LOOPING, HEALTH_BAD, HEALTH_MAINTENANCE, HEALTH_RETIRED = range(
        6
    )
    HEALTH_CHOICES = (
        (HEALTH_GOOD, "Good"),
        (HEALTH_UNKNOWN, "Unknown"),
        (HEALTH_LOOPING, "Looping"),
        (HEALTH_BAD, "Bad"),
        (HEALTH_MAINTENANCE, "Maintenance"),
        (HEALTH_RETIRED, "Retired"),
    )
    HEALTH_REVERSE = {
        "Good": HEALTH_GOOD,
        "Unknown": HEALTH_UNKNOWN,
        "Looping": HEALTH_LOOPING,
        "Bad": HEALTH_BAD,
        "Maintenance": HEALTH_MAINTENANCE,
        "Retired": HEALTH_RETIRED,
    }

    health = models.IntegerField(choices=HEALTH_CHOICES, default=HEALTH_UNKNOWN)

    def __str__(self):
        return "%s@%s <%s> (%s)" % (
            self.name,
            self.lab,
            self.dt,
            self.get_health_display(),
        )

    def master_name(self):
        return "%s@%s" % (self.name, self.lab.name)


class DeviceType(models.Model):
    name = models.CharField(primary_key=True, max_length=200)

    def __str__(self):
        return "%s" % self.name


class Feature(models.Model):
    name = models.CharField(primary_key=True, max_length=200)
    description = models.TextField(null=True, blank=True)

    TYPE_GENERIC, TYPE_DEVICE = range(2)
    TYPE_CHOICES = ((TYPE_GENERIC, "Generic"), (TYPE_DEVICE, "Device"))
    type = models.IntegerField(choices=TYPE_CHOICES, default=TYPE_GENERIC)

    ACTION_NONE, ACTION_DEPLOY, ACTION_BOOT, ACTION_TEST = range(4)
    ACTION_CHOICES = (
        (ACTION_NONE, "None"),
        (ACTION_DEPLOY, "Deploy"),
        (ACTION_BOOT, "Boot"),
        (ACTION_TEST, "Test"),
    )
    action = models.IntegerField(choices=ACTION_CHOICES, default=ACTION_NONE)

    def __str__(self):
        return "%s" % self.name

    @classmethod
    def reverse_action(cls, action_str):
        action_str = action_str.lower()
        for (a, s) in cls.ACTION_CHOICES:
            if action_str == s.lower():
                return a
        return None

    @classmethod
    def reverse_type(cls, type_str):
        type_str = type_str.lower()
        for (t, s) in cls.TYPE_CHOICES:
            if type_str == s.lower():
                return t
        return None


class Job(models.Model):
    name = models.CharField(blank=False, max_length=255)
    device = models.ForeignKey("Device", on_delete=models.CASCADE)
    version = models.ForeignKey("Version", on_delete=models.CASCADE)
    lava = models.IntegerField(default=0, verbose_name="Lava job id")
    url = models.URLField(default="")
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    features = models.ManyToManyField(Feature, blank=True)

    ARCH_AMD64, ARCH_AARCH64 = range(2)
    ARCH_CHOICES = ((ARCH_AMD64, "amd64"), (ARCH_AARCH64, "aarch64"))
    ARCH_REVERSE = {"amd64": ARCH_AMD64, "aarch64": ARCH_AARCH64}
    arch = models.IntegerField(choices=ARCH_CHOICES, default=ARCH_AMD64)

    TYPE_FED, TYPE_SLAVE, TYPE_META, TYPE_PACKAGE = range(4)
    TYPE_CHOICES = (
        (TYPE_FED, "FED"),
        (TYPE_SLAVE, "SLAVE"),
        (TYPE_META, "META"),
        (TYPE_PACKAGE, "PACKAGE"),
    )
    type = models.IntegerField(choices=TYPE_CHOICES, default=TYPE_FED)

    HEALTH_UNKNOWN, HEALTH_COMPLETE, HEALTH_INCOMPLETE, HEALTH_CANCELED = range(4)
    HEALTH_CHOICES = (
        (HEALTH_UNKNOWN, "Unknown"),
        (HEALTH_COMPLETE, "Complete"),
        (HEALTH_INCOMPLETE, "Incomplete"),
        (HEALTH_CANCELED, "Canceled"),
    )
    HEALTH_REVERSE = {
        "Unknown": HEALTH_UNKNOWN,
        "Complete": HEALTH_COMPLETE,
        "Incomplete": HEALTH_INCOMPLETE,
        "Canceled": HEALTH_CANCELED,
    }
    health = models.IntegerField(choices=HEALTH_CHOICES, default=HEALTH_UNKNOWN)

    def __str__(self):
        return "%s (%s)" % (self.name, self.device)


class Lab(models.Model):
    name = models.CharField(primary_key=True, max_length=200)
    url = models.URLField()

    def __str__(self):
        return "%s" % self.name

    def devices(self):
        return self.device_set.select_related("dt").order_by("dt__name")

    def last_slave(self):
        jobs = Job.objects.filter(device__lab=self)
        ret = jobs.filter(type=Job.TYPE_SLAVE).order_by("version").last()
        if ret:
            return ret
        return jobs.filter(type=Job.TYPE_META).order_by("version").last()


class Token(models.Model):
    token = models.CharField(max_length=64, default=_make_secret)
    description = models.CharField(blank=True, null=True, max_length=150)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("token", "lab")

    def __str__(self):
        return "%s - %s" % (self.lab.name, self.description)


class Version(models.Model):
    version = models.CharField(primary_key=True, max_length=200)

    def __str__(self):
        return "%s" % self.version

lavafed/templates/lavafed/base.html
<!doctype html>{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="{% static "lavafed/css/bootstrap-v4.2.1.min.css" %}">
  <link rel="stylesheet" href="{% static "lavafed/css/fontawesome-v5.4.1.min.css" %}">
  <style>
    body > .container {
      padding: 30px 15px 0;
    }
    {% block style %}{% endblock style %}
  </style>
  <title>lavafed{% block title %}{% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="https://federation.lavasoftware.org"><i class="fab fa-trade-federation"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsToggle" aria-controls="navbarsToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsToggle">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% block nav_home %}{% endblock %}">
          <a class="nav-link" href="{% url "home" %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% block nav_devices %}{% endblock %}">
          <a class="nav-link" href="{% url "devices" %}">Devices</a>
        </li>
        <li class="nav-item {% block nav_device_types %}{% endblock %}">
          <a class="nav-link" href="{% url "device_types" %}">Device-types</a>
        </li>
        <li class="nav-item {% block nav_labs %}{% endblock %}">
          <a class="nav-link" href="{% url "labs" %}">Labs</a>
        </li>
        <li class="nav-item {% block nav_versions %}{% endblock %}">
          <a class="nav-link" href="{% url "versions" %}">Versions</a>
        </li>
      </ul>
    </div>
  </nav>

  <main class="container">
  {% block body %}{% endblock body %}
  </main>

  <script src="{% static "lavafed/js/jquery-v3.4.1.slim.min.js" %}"></script>
  <script src="{% static "lavafed/js/popper-v1.14.6.min.js" %}"></script>
  <script src="{% static "lavafed/js/bootstrap-v4.2.1.min.js" %}"></script>
  {% block scripts %}{% endblock %}
</body>
</html>

lavafed/templates/lavafed/device_type_show.html
{% extends 'lavafed/base.html' %}

{% block title %} - device type {{ dt.name }}{% endblock %}

{% block nav_device_types %}active{% endblock %}

{% block body %}
<div class="row">
  <div class="col">
    <h4>Devices</h4>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>name</th>
          <th>lab</th>
          <th>acquired</th>
        </tr>
      </thead>
      <tbody>
        {% for device in devices %}
        <tr>
          <td><a href="{% url "device.show" device.lab.name device.name %}">{{ device.name }}</a></td>
          <td><a href="{% url "labs.show" device.lab.name %}">{{ device.lab.name }}</a></td>
          {% if device.acquired %}
          <td title="Acquired"><i class="text-success far fa-check-circle"></i></td>
          {% else %}
          <td title="Released"><i class="text-danger far fa-circle"></i></td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <h4>Jobs {% if jobs.paginator.num_pages > 1 %}(page {{ jobs.number }} / {{jobs.paginator.num_pages }}){% endif %}</h4>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>name</th>
          <th>device</th>
          <th>version</th>
          <th>health</th>
          <th>slave</th>
          <th>type</th>
        </tr>
      </thead>
      <tbody>
        {% for job in jobs %}
        {% ifchanged job.version.version %}
        {% if not forloop.first %}
      </tbody>
      <tbody>
        {% endif %}
        {% endifchanged %}
        <tr>
          <td>{{ job.name }}</td>
          <td><a href="{% url "device.show" job.device.lab.name job.device.name %}">{{ job.device.name }}</a></td>
          <td><a href="{% url 'versions.show' job.version.version %}">{{ job.version.version }}</a></td>
          <td title="{{ job.get_health_display }}">
            {% if job.get_health_display == "Unknown" %}
            <i class="text-secondary far fa-question-circle"></i>
            {% elif job.get_health_display == "Complete" %}
            <i class=" text-success fas fa-check-circle"></i>
            {% elif job.get_health_display == "Incomplete" %}
            <i class="text-danger fas fa-exclamation-circle"></i>
            {% else %}
            <i class="text-warning fas fa-ban"></i>
            {% endif %}
          </td>
          <td>{{ job.get_arch_display }}</td>
          <td>{{ job.get_type_display }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% if jobs.has_previous %}
    <a href=".?page={{ jobs.previous_page_number }}{% if "per_pages" in request.GET %}&per_pages={{ request.GET.per_pages }}{% endif %}" class="btn btn-info"><i class="fas fa-backward"></i> Previous</a>
  {% endif %}
  {% if jobs.has_next %}
    <a href=".?page={{ jobs.next_page_number }}{% if "per_pages" in request.GET %}&per_pages={{ request.GET.per_pages }}{% endif %}" class="btn btn-info float-right">Next <i class="fas fa-forward"></i></a>
  {% endif %}
  </div>
</div>
{% endblock body %}

lavafed/templates/lavafed/device_types.html
{% extends 'lavafed/base.html' %}

{% block title %} - device types{% endblock %}

{% block nav_device_types %}active{% endblock %}

{% block body %}
<div class="row">
  <div class="col">
    <h4>Device Types</h4>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>name</th>
          <th>devices</th>
          <th>jobs</th>
        </tr>
      </thead>
      <tbody>
        {% for dt in dts %}
        <tr>
          <td><a href="{% url "device_types.show" dt.name %}">{{ dt.name }}</a></td>
          <td>{{ dt.device__count }}</td>
          <td>{{ dt.device__job__count }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock body %}

lavafed/templates/lavafed/lab_show.html
{% extends 'lavafed/base.html' %}

{% block title %} - lab {{ lab.name }}{% endblock %}

{% block nav_labs %}active{% endblock %}

{% block body %}
<div class="row">
  <div class="col">
    <h4>Devices</h4>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>name</th>
          <th>type</th>
          <th>acquired</th>
        </tr>
      </thead>
      <tbody>
        {% for device in lab.devices %}
        <tr>
          <td><a href="{% url "device.show" device.lab.name device.name %}">{{ device.name }}</a></td>
          <td><a href="{% url "device_types.show" device.dt.name %}">{{ device.dt.name }}</a></td>
          {% if device.acquired %}
          <td title="Acquired"><i class="text-success far fa-check-circle"></i></td>
          {% else %}
          <td title="Released"><i class="text-danger far fa-circle"></i></td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <h4>Jobs {% if jobs.paginator.num_pages > 1 %}(page {{ jobs.number }} / {{ jobs.paginator.num_pages }}){% endif %}</h4>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>name</th>
          <th>device</th>
          <th>version</th>
          <th>health</th>
          <th>slave</th>
          <th>type</th>
        </tr>
      </thead>
      <tbody>
        {% for job in jobs %}
          {% ifchanged job.version.version %}
          {% if not forloop.first %}
      </tbody>
      <tbody>
          {% endif %}
          {% endifchanged %}
        <tr>
          <td>{{ job.name }}</td>
          <td><a href="{% url "device.show" job.device.lab.name job.device.name %}">{{ job.device.name }}</a></td>
          <td><a href="{% url 'versions.show' job.version.version %}">{{ job.version.version }}</a></td>
          <td title="{{ job.get_health_display }}">
            {% if job.get_health_display == "Unknown" %}
            <i class="text-secondary far fa-question-circle"></i>
            {% elif job.get_health_display == "Complete" %}
            <i class=" text-success fas fa-check-circle"></i>
            {% elif job.get_health_display == "Incomplete" %}
            <i class="text-danger fas fa-exclamation-circle"></i>
            {% else %}
            <i class="text-warning fas fa-ban"></i>
            {% endif %}
          </td>
          <td>{{ job.get_arch_display }}</td>
          <td>{{ job.get_type_display }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% if jobs.has_previous %}
    <a href=".?page={{ jobs.previous_page_number }}{% if "per_pages" in request.GET %}&per_pages={{ request.GET.per_pages }}{% endif %}" class="btn btn-info"><i class="fas fa-backward"></i> Previous</a>
  {% endif %}
  {% if jobs.has_next %}
    <a href=".?page={{ jobs.next_page_number }}{% if "per_pages" in request.GET %}&per_pages={{ request.GET.per_pages }}{% endif %}" class="btn btn-info float-right">Next <i class="fas fa-forward"></i></a>
  {% endif %}
  </div>
</div>

{% endblock body %}

lavafed/templates/lavafed/version_show.html
{% extends 'lavafed/base.html' %}
{% load features %}

{% block title %} - version - {{ version.version }}{% endblock %}

{% block nav_versions %}active{% endblock %}

{% block body %}
<div class="row">
  <div class="col">

    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Jobs</a>
      </li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>name</th>
              <th>description</th>
              <th>result</th>
            </tr>
          </thead>
          <tbody>
            {% for feature in global_features %}
            {% feature_results feature version as feature_jobs %}
            <tr>
              <td>{{ feature.name }}</td>
              <td>{{ feature.description }}</td>
              <td>
              {% for job in feature_jobs %}
                {% if job.health == job.HEALTH_UNKNOWN %}
                <i class="text-secondary far fa-question-circle" title="{{ job.name }}"></i>
                {% elif job.health == job.HEALTH_COMPLETE %}
                <i class=" text-success fas fa-check-circle" title="{{ job.name }}"></i>
                {% elif job.health == job.HEALTH_INCOMPLETE %}
                <i class="text-danger fas fa-exclamation-circle" title="{{ job.name }}"></i>
                {% else %}
                <i class="text-warning fas fa-ban" title="{{ job.name }}">
                {% endif %}
              {% endfor %}
              </td>
            </tr>
            {% empty %}
            <tr>
              <td><i>...</i></td>
              <td><i>...</i></td>
              <td><i>...</i></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>name</th>
              <th>deploy</th>
              <th>boot</th>
              <th>test</th>
            </tr>
          </thead>
          <tbody>
            {% for dt in dts %}
            {% features dt version True "Device" "Deploy" as deploy_features_pass %}
            {% features dt version True "Device" "Boot" as boot_features_pass %}
            {% features dt version True "Device" "Test" as test_features_pass %}
            {% features dt version False "Device" "Deploy" as deploy_features_fail %}
            {% features dt version False "Device" "Boot" as boot_features_fail %}
            {% features dt version False "Device" "Test" as test_features_fail %}
            <tr>
              <td>{{ dt.name }}</td>
              <td>{% if deploy_features_pass %}
                    <i class=" text-success fas fa-check-circle"></i> {% for f in deploy_features_pass %}<abbr title="{{ f.description }}">{{ f.name|slice:"7:" }}</abbr>{% if not forloop.last %}, {% endif %}{% endfor %}<br />
                  {% endif %}{% if deploy_features_fail %}
                    <i class=" text-danger fas fa-exclamation-circle"></i> {% for f in deploy_features_fail %}<abbr title="{{ f.description }}">{{ f.name|slice:"7:" }}</abbr>{% if not forloop.last %}, {% endif %}{% endfor %}
                  {% endif %}{% if not deploy_features_pass and not deploy_features_fail %}<i>...</i>{% endif %}</td>
              <td>{% if boot_features_pass %}
                    <i class=" text-success fas fa-check-circle"></i> {% for f in boot_features_pass %}<abbr title="{{ f.description }}">{{ f.name|slice:"5:" }}</abbr>{% if not forloop.last %}, {% endif %}{% endfor %}<br />
                  {% endif %}{% if boot_features_fail %}
                    <i class=" text-danger fas fa-exclamation-circle"></i> {% for f in boot_features_fail %}<abbr title="{{ f.description }}">{{ f.name|slice:"5:" }}</abbr>{% if not forloop.last %}, {% endif %}{% endfor %}
                  {% endif %}{% if not boot_features_pass and not boot_features_fail %}<i>...</i>{% endif %}</td>
              <td>{% if test_features_pass %}
                    <i class=" text-success fas fa-check-circle"></i> {% for f in test_features_pass %}<abbr title="{{ f.description }}">{{ f.name|slice:"5:" }}</abbr>{% if not forloop.last %}, {% endif %}{% endfor %}<br />
                  {% endif %}{% if test_features_fail %}
                    <i class=" text-danger fas fa-exclamation-circle"></i> {% for f in test_features_fail %}<abbr title="{{ f.description }}">{{ f.name|slice:"5:" }}</abbr>{% if not forloop.last %}, {% endif %}{% endfor %}
                  {% endif %}{% if not test_features_pass and not test_features_fail %}<i>...</i>{% endif %}</td>
            </tr>
            {% empty %}
            <tr>
              <td><i>...</i></td>
              <td><i>...</i></td>
              <td><i>...</i></td>
              <td><i>...</i></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      <div class="tab-pane" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>type</th>
              <th>name</th>
              <th>device</th>
              <th>lab</th>
              <th>slave</th>
              <th>type</th>
              <th>health</th>
            </tr>
          </thead>
          <tbody>
            {% for job in global_jobs %}
            <tr>
              <td><a href="{% url "device_types.show" job.device.dt.name %}">{{ job.device.dt.name }}</a></td>
              <td>{{ job.name }}{% if job.url %} <a href="{{ job.url }}"><i class="fas fa-link"></i></a>{% endif %}</td>
              <td><a href="{% url "device.show" job.device.lab.name job.device.name %}">{{ job.device.name }}</a></td>
              <td><a href="{% url "labs.show" job.device.lab.name %}">{{ job.device.lab.name }}</a></td>
              <td>{{ job.get_arch_display }}</td>
              <td>{{ job.get_type_display }}</td>
              <td title="{{ job.get_health_display }}">
                {% if job.get_health_display == "Unknown" %}
                <i class="text-secondary far fa-question-circle"></i>
                {% elif job.get_health_display == "Complete" %}
                <i class=" text-success fas fa-check-circle"></i>
                {% elif job.get_health_display == "Incomplete" %}
                <i class="text-danger fas fa-exclamation-circle"></i>
                {% else %}
                <i class="text-warning fas fa-ban"></i>
                {% endif %}
              </td>
            </tr>
            {% empty %}
            <td>...</td>
            <td>...</td>
            <td>...</td>
            <td>...</td>
            <td>...</td>
            <td>...</td>
            <td>...</td>
            {% endfor %}
          </tbody>
        </table>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>type</th>
              <th>name</th>
              <th>device</th>
              <th>lab</th>
              <th>slave</th>
              <th>health</th>
            </tr>
          </thead>
          <tbody>
            {% for job in device_jobs %}
            <tr>
              <td><a href="{% url "device_types.show" job.device.dt.name %}">{{ job.device.dt.name }}</a></td>
              <td>{{ job.name }}{% if job.url %} <a href="{{ job.url }}"><i class="fas fa-link"></i></a>{% endif %}</td>
              <td><a href="{% url "device.show" job.device.lab.name job.device.name %}">{{ job.device.name }}</a></td>
              <td><a href="{% url "labs.show" job.device.lab.name %}">{{ job.device.lab.name }}</a></td>
              <td>{{ job.get_arch_display }}</td>
              <td title="{{ job.get_health_display }}">
                {% if job.get_health_display == "Unknown" %}
                <i class="text-secondary far fa-question-circle"></i>
                {% elif job.get_health_display == "Complete" %}
                <i class=" text-success fas fa-check-circle"></i>
                {% elif job.get_health_display == "Incomplete" %}
                <i class="text-danger fas fa-exclamation-circle"></i>
                {% else %}
                <i class="text-warning fas fa-ban"></i>
                {% endif %}
              </td>
            </tr>
            {% empty %}
            <td>...</td>
            <td>...</td>
            <td>...</td>
            <td>...</td>
            <td>...</td>
            <td>...</td>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock body %}